/**
 * Copyright (c) 6/7/2016 Virtual Object Sv AB
 * Created by Orhan Mekic on 6/7/2016.
 */

const actions = {
   BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
   AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
   LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
   LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
   CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
   UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',

   LOAD_PATIENTS_SUCCESS: 'LOAD_PATIENTS_SUCCESS'
};

export default actions;
